  create table user_ (
       dtype varchar(31) not null,
        id int4 generated by default as identity,
        city varchar(255),
        cpf varchar(255),
        email varchar(255),
        _from varchar(255),
        name_father varchar(255),
        name_mother varchar(255),
        number_street varchar(255),
        password varchar(255),
        phone varchar(255),
        sex int4,
        state varchar(255),
        street varchar(255),
        username varchar(255),
        zip_code varchar(255),
        crm varchar(255),
        specialty varchar(255),
        symptoms varchar(255),
        primary key (id)
    );

   