 create table agendamento (
       id int4 generated by default as identity,
        date_closed timestamp,
        date_open timestamp,
        description varchar(255),
        priority int4,
        status int4,
        medical_id int4,
        patient_id int4,
        primary key (id)
    );
